commands:
- actions:
  - keyboard:
      hold: 0.3
      hotkey: p
      hotkey_codes:
      - 25
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - wipers on
  - activate wipers
  - wipers off
  is_system_command: false
  name: NextWindshieldWipersMode
  responses:
  - wiper mode changed
  - wipers toggled
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f
      hotkey_codes:
      - 33
  force_instant_activation: false
  instant_activation:
  - toggle hazard lights
  - turn off hazard lights
  - turn hazard lights on
  - flashers on
  - flashers off
  is_system_command: false
  name: ToggleHazardLights
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: r
      hotkey_codes:
      - 19
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - radio on
  - radio off
  is_system_command: false
  name: ToggleRadio
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: page up
      hotkey_codes:
      - 73
      hotkey_extended: true
  force_instant_activation: false
  instant_activation:
  - next radio station
  - change radio station
  is_system_command: false
  name: NextRadioStation
  responses:
  - ok.
  - got it.
  - radio station changed
- actions:
  - keyboard:
      hold: 0.3
      hotkey: page down
      hotkey_codes:
      - 81
      hotkey_extended: true
  force_instant_activation: false
  instant_activation:
  - last radio station
  - previous radio station
  is_system_command: false
  name: PreviousRadioStation
  responses:
  - ok.
  - got it
  - radio station changed
- actions:
  - keyboard:
      hold: 0.3
      hotkey: k
      hotkey_codes:
      - 37
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - high beams on
  - high beams off
  - beacons on
  - beacons off
  is_system_command: false
  name: ToggleHighBeams
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: c
      hotkey_codes:
      - 46
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - cruise control on
  - cruise control off
  is_system_command: false
  name: ToggleCruiseControl
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: t
      hotkey_codes:
      - 20
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - connect trailer
  - disconnect trailer
  is_system_command: false
  name: ConnectOrDisconnectTrailer
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: space
      hotkey_codes:
      - 57
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - parking brake on
  - parking brake off
  - toggle parking brake
  is_system_command: false
  name: ToggleParkingBrake
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: e
      hotkey_codes:
      - 18
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - start engine
  - engine on
  is_system_command: false
  name: StartEngine
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: e
      hotkey_codes:
      - 18
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - engine off
  is_system_command: false
  name: TurnOffEngine
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f5
      hotkey_codes:
      - 63
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - show the map
  - show map
  - activate navigation map
  is_system_command: false
  name: ShowNavigationMapPage
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f7
      hotkey_codes:
      - 65
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - diagnostics
  - truck info
  is_system_command: false
  name: ShowDiagnosticsTruckInfo
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f3
      hotkey_codes:
      - 61
      hotkey_extended: false
  force_instant_activation: false
  instant_activation: []
  is_system_command: false
  name: SwitchRouteAdvisorModes
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f12
      hotkey_codes:
      - 88
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - reset view
  - recenter view
  is_system_command: false
  name: RecenterView
  responses:
  - view recentered
- actions:
  - keyboard:
      hold: 0.3
      hotkey: '['
      hotkey_codes:
      - 26
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - left signal on
  - left signal off
  - toggle left signal
  - left blinker on
  - right blinker off
  is_system_command: false
  name: ToggleLeftTurnSignal
  responses:
  - left signal command accepted
- actions:
  - keyboard:
      hold: 0.3
      hotkey: ']'
      hotkey_codes:
      - 27
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - right signal on
  - right signal off
  - right blinker on
  - right blinker off
  - toggle right blinker
  is_system_command: false
  name: ToggleRightTurnSignal
  responses:
  - right signal command accepted
- actions:
  - keyboard:
      hold: 0.3
      hotkey: enter
      hotkey_codes:
      - 28
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - press enter
  - confirm dialog
  is_system_command: false
  name: ConfirmSelection
  responses:
  - got it
- actions:
  - keyboard:
      hold: 0.3
      hotkey: l
      hotkey_codes:
      - 38
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - headlights on
  - headlights off
  - torch on
  - torch off
  - change headlight mode
  is_system_command: false
  name: NextHeadlightsMode
  responses:
  - headlight mode changed
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f2
      hotkey_codes:
      - 60
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - hide the mirrors
  - change mirror mode
  - toggle mirrors
  is_system_command: false
  name: ChangeMirrorsMode
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f1
      hotkey_codes:
      - 59
      hotkey_extended: false
  force_instant_activation: false
  instant_activation: []
  is_system_command: false
  name: UseMouseControl
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f6
      hotkey_codes:
      - 64
      hotkey_extended: false
  force_instant_activation: false
  instant_activation: []
  is_system_command: false
  name: ShowJobInfo
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: num0
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - next route advisor page
  - change route advisor page
  is_system_command: false
  name: NextRouteAdvisorPage
  responses:
  - page switched.
- actions:
  - keyboard:
      hold: 0.3
      hotkey: y
      hotkey_codes:
      - 21
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - i want to chat
  - show me the chat
  - open the chat window
  - close the chat window
  - open chat window
  - close chat window
  is_system_command: false
  name: OpenChatMode
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f1
      hotkey_codes:
      - 59
      hotkey_extended: false
  force_instant_activation: false
  instant_activation: []
  is_system_command: false
  name: PauseGame
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f9
      hotkey_codes:
      - 67
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - activate route advisor chat page
  - show me the chat page
  - show me the route advisor chat page
  - display route advisor chat page
  is_system_command: false
  name: RouteAdvisorChatPage
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: esc
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - close chat mode
  - exit chat mode
  - close chat window
  - close the chat
  - close chat
  is_system_command: false
  name: CloseChatMode
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: esc
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - open the main menu
  - open main menu
  is_system_command: false
  name: OpenMainMenu
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: esc
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - go back
  - close menu
  - close this menu
  is_system_command: false
  name: GoBackOrCloseMenu
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f1
      hotkey_codes:
      - 59
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - unpause
  is_system_command: false
  name: UnpauseGame
  responses: []
- actions:
  - keyboard:
      hold: 10.0
      hotkey: enter
      hotkey_codes:
      - 28
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - refuel
  is_system_command: false
  name: Refuel
  responses:
  - refueling now
  - gassing up
  - you got it
  - filling your tank
  - getting you full
- actions:
  - keyboard:
      hold: 0.3
      hotkey: enter
      hotkey_codes:
      - 28
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - press enter
  is_system_command: false
  name: PressEnter
  responses:
  - done
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f5
      hotkey_codes:
      - 63
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - zoom out the map
  - change the map zoom level
  - change map zoom
  - toggle map zoom
  name: ChangeMapZoomLevel
  responses:
  - changing map zoom level
  - got it
  - adjusting map mode
  - toggling map display
- actions:
  - keyboard:
      hold: 6.0
      hotkey: x
      hotkey_codes:
      - 45
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - press the push to talk button
  - push to talk
  - activate push to talk
  - activate ptt
  name: PushToTalk
  responses:
  - ptt ended
  - push to talk ended
- actions:
  - keyboard:
      hold: 1.0
      hotkey: n
      hotkey_codes:
      - 49
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - blow the air horn
  - sound the air horn
  - activate the air horn
  - blow the horn
  name: ActivateAirHorn
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: f4
      hotkey_codes:
      - 62
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - adjust my truck seat
  - truck adjustment menu
  - truck adjust menu
  name: AdjustTruckSeat
  responses: []
- actions:
  - keyboard:
      hold: 0.3
      hotkey: '9'
      hotkey_codes:
      - 10
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - next camera
  name: NextCamera
  responses:
  - got it
  - next camera selected
  - camera mode toggled
- actions:
  - keyboard:
      hold: 0.3
      hotkey: '1'
      hotkey_codes:
      - 2
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - interior camera
  - inside camera
  name: InteriorCameraMode
  responses:
  - interior camera mode displayed
  - inside camera mode activated
- actions:
  - keyboard:
      hold: 0.3
      hotkey: '2'
      hotkey_codes:
      - 3
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - chasing camera mode
  name: ChasingCamera
  responses:
  - chasing camera mode activated
  - chasing camera mode on
- actions:
  - keyboard:
      hold: 0.3
      hotkey: '8'
      hotkey_codes:
      - 9
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - activate drive by camera
  - turn on drive by camera
  - switch to drive by camera
  name: DriveByCamera
  responses:
  - drive by camera mode activated
  - activated drive by cam
  - switched camera mode to drive by
- actions:
  - keyboard:
      hold: 0.3
      hotkey: q
      hotkey_codes:
      - 16
      hotkey_extended: false
  force_instant_activation: false
  instant_activation:
  - quick replies
  name: ToggleQuickRepliesMenu
  responses:
  - quick replies menu toggled
description: ''
disabled: false
features:
  use_generic_instant_responses: true
is_voice_activation_default: true
name: Assistant
prompts:
  backstory: "You are the AI assistant built into the dashboard of a big rig truck.\
    \  You assist with performing vehicle functions efficiently and in a friendly\
    \ manner.  Like a normal vehicle AI assistant you respond in a short, clear and\
    \ concise manner to confirm the user's actions or request clarification if need,\
    \ as you understand that the driver needs to focus their attention on the road\
    \ at all times and distractions caused by long responses can cause accidents and\
    \ grave injury. \n\nYou also have access to search the web using the web_search\
    \ function to specifically search the Truck Simulator wiki for information about\
    \ the game.  If the user asks information about the game itself, you should search\
    \ the Truck Simulator wiki using the web_search skill before answering to ensure\
    \ you have up to date information.  You should use the single site search to do\
    \ so, and the format of the single site is: https://trucksimulator.wiki.gg/index.php?search=cities&title=Special%3ASearch&profile=advanced&fulltext=1&ns0=1.\
    \  Example:\n(1) User request: \"What cities are in American Truck Simulator?\"\
    \nResponse: -> You perform a single site search using the web_search skill, using\
    \ this URL and answer using the provided contents:  https://trucksimulator.wiki.gg/index.php?search=cities+in+american+truck+simulator&title=Special%3ASearch&profile=advanced&fulltext=1&ns0=1.\n\
    (2) User request: \"What companies are in Euro Truck Simulator?\"\nResponse: ->\
    \ You perform a single site search using the web_search skill, using this URL\
    \ and answer using the provided contents: ttps://trucksimulator.wiki.gg/index.php?search=companies+in+euro+truck+simulator&title=Special%3ASearch&profile=advanced&fulltext=1&ns0=1.\n\
    \nImportant style notes: (1) remember you are speaking to the driver, so use plain\
    \ declarative sentences not emojis or lists since those cannot be easily verbalized:\
    \ (2) if the driver wants something done, just do it, assume that the driver is\
    \ correct in their request and that the last information you had may have changed;\
    \ (3) always prefer getting fresh data rather than relying on old data if the\
    \ driver requests information about the truck, route, time or similar things;\
    \ and (4) remember you can chain commands together  -- for instance, if the driver\
    \ asks what time they will get to a certain destination remember you can first\
    \ get the current gameTime, then use routeTime to get the estimated amount of\
    \ time to complete the route, and then add that time to the gameTime to get an\
    \ estimate of the time when the user will arrive -- that's just an example, use\
    \ this ability whenever you need in order to accomplish the driver's goal."
record_key: \
record_key_codes:
- 43
skills:
- examples:
  - answer:
      de: Ich habe folgende Neuigkeiten zu Star Citizen gefunden...
      en: I found the following news about Star Citizen...
    question:
      de: Suche im Internet nach aktuellen Neuigkeiten zu Star Citizen und fasse sie
        zusammen.
      en: Search the internet for recent news about Star Citizen and give me the highlights.
  module: skills.web_search.main
- custom_properties:
  - id: display
  - id: show_screenshots
  examples:
  - answer:
      de: Ich sehe die Spotify-App, die Musik abspielt.
      en: I see Spotify running and playing music.
    question:
      de: Was siehst du auf meinem Bildschirm?
      en: What is on my screen?
  module: skills.vision_ai.main
- custom_properties:
  - id: quick_commands_learning_rule_count
  module: skills.quick_commands.main
- examples:
  - answer:
      de: (Tippt "Wie geht's dir heute?" im aktiven Fenster an der aktuellen Cursor-Position
        ein)
      en: (types "How are you today?" in active window at the current cursor location)
    question:
      de: Tippe "Wie geht's dir heute?".
      en: Type "How are you today?".
  - answer:
      de: "(Erfindet ein Gedicht \xFCber B\xE4ume und tippt es dann in das aktive\
        \ Fenster)"
      en: (imagines a poem about trees and then types it in the active window)
    question:
      de: "Schreibe ein Gedicht \xFCber B\xE4ume."
      en: Type a poem about trees.
  module: skills.typing_assistant.main
- custom_properties:
  - id: use_metric_system
  - id: ats_install_directory
  - id: ets_install_directory
  - id: dispatcher_backstory
  - id: autostart_dispatch_mode
  examples:
  - answer:
      de: "(gibt die aktuelle Geschwindigkeit zur\xFCck)"
      en: (returns the current speed)
    question:
      de: Was ist meine aktuelle Geschwindigkeit?
      en: What is my current speed?
  - answer:
      de: (aktiviert / deaktiviert den Versandmodus)
      en: (activates / deactivates dispatch mode)
    question:
      de: Aktiviere den Versandmodus / Beende den Versandmodus.
      en: Activate the dispatch mode / Stop dispatch mode.
  module: skills.ats_telemetry.main
- custom_properties:
  - id: default_directory
  - id: allow_overwrite_existing
  examples:
  - answer:
      de: (speichert 'Hallo, Welt!' in hello.txt im Standardverzeichnis)
      en: (saves 'Hello, World!' to hello.txt in the default directory)
    question:
      de: Speichere 'Hallo, Welt!' in hello.txt.
      en: Save 'Hello, World!' to hello.txt.
  - answer:
      de: "(l\xE4dt den Inhalt von notes.md und liest ihn vor)"
      en: (loads the content of notes.md and reads it out loud)
    question:
      de: Lade den Inhalt aus notes.md.
      en: Load the content from notes.md.
  - answer:
      de: (erstellt ein Verzeichnis namens 'Projekte' im Standardverzeichnis)
      en: (creates a directory named 'Projects' in the default directory)
    question:
      de: Erstelle ein Verzeichnis namens 'Projekte'.
      en: Create a directory named 'Projects'.
  module: skills.file_manager.main
- custom_properties:
  - id: display
  - id: default_directory
  examples:
  - answer:
      de: (Macht einen Screenshot des fokussierten Fensters)
      en: (Takes a screenshot of the focused window)
    question:
      de: Mach einen Screenshot
      en: Take a screenshot
  - answer:
      de: (Macht einen Screenshot des fokussierten Fensters)
      en: (Takes a screenshot of the focused window)
    question:
      de: "Oh wow das ist verr\xFCckt!"
      en: Oh wow this is crazy!
  module: skills.auto_screenshot.main
